/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto;

import javax.swing.table.DefaultTableModel;
import java.util.Date;
import java.time.LocalDateTime;
import javax.swing.JOptionPane;
import java.awt.*;
import java.awt.print.*;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;

/**
 *
 * @author paola
 */
public class frmGenerarOrdenCompra extends javax.swing.JInternalFrame implements Printable {

    //Objetos instanciados
    Connection con = null;
    Statement stmt = null;

    //Varibles Globles
    SolicitudesConexion soliConecta = new SolicitudesConexion();
    Solicitud soli = new Solicitud();
    Conexion c = new Conexion();
    DefaultTableModel modelo = new DefaultTableModel();
    DefaultTableModel modeloAprobado = new DefaultTableModel();

    //Arrays
    String titulos[] = {"Id", "Usuario", "Producto", "Precio", "Cantidad", "Estado"};
    String titulosAprobados[] = {"Producto", "Cantidad", "Precio", "Total"};
    String fila[] = new String[6];
    String filaAprobacio[] = new String[4];

    /**
     * Creates new form GenerarOrdenCompra
     */
    public frmGenerarOrdenCompra() {
        initComponents();

        //Metodos de la fecha y hora Actuales
        SimpleDateFormat dFormat = new SimpleDateFormat("dd/MM/yyyy");
        Date date = new Date();
        lblFechaActual.setText(dFormat.format(date));

        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("HH:mm:ss");
        LocalDateTime now = LocalDateTime.now();
        lblHoraActual.setText(dtf.format(now));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void calcularTotal() {
        double S = 0, iva, tot;
        //Array que recorre toda la tabla
        for (int i = 0; i < tableAprobaciones.getRowCount(); i++) {
            S = S + Double.parseDouble(modeloAprobado.getValueAt(i, 3).toString());
        }
        //Aqui realizamos los calculos de lo que se debe pagar
        S = redondear(S);
        txtSubTotal.setText(String.valueOf(S));
        iva = 0.015 * S;
        iva = redondear(iva);
        tot = S * 1.15;
        tot = redondear(tot);
        txtTotalIVA.setText(String.valueOf(iva));
        txtTotal.setText(String.valueOf(tot));
    }

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jFrame1 = new javax.swing.JFrame();
        panelGenerarOrdenCompra = new javax.swing.JPanel();
        lblFecha = new javax.swing.JLabel();
        panelTableDetalleProductos = new javax.swing.JScrollPane();
        tableAprobaciones = new javax.swing.JTable();
        lblDetalleProductos = new javax.swing.JLabel();
        lblSubTotal = new javax.swing.JLabel();
        txtSubTotal = new javax.swing.JTextField();
        lblTotalIVA = new javax.swing.JLabel();
        txtTotalIVA = new javax.swing.JTextField();
        lblTotal = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        btnImprimir = new javax.swing.JButton();
        lblFecha1 = new javax.swing.JLabel();
        btnCalcularTotal = new javax.swing.JButton();
        lblFechaActual = new javax.swing.JLabel();
        lblHoraActual = new javax.swing.JLabel();
        lblProducto = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        btnBuscar = new javax.swing.JButton();
        panelTableDetalleProductos1 = new javax.swing.JScrollPane();
        tableDetallePedido = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        panelGenerarOrdenCompra.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Compra", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        lblFecha.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblFecha.setText("Hora:");

        tableAprobaciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Producto", "Cantidad", "Precio Unitario", "SubTotal"
            }
        ));
        tableAprobaciones.setGridColor(new java.awt.Color(240, 240, 240));
        panelTableDetalleProductos.setViewportView(tableAprobaciones);

        lblDetalleProductos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblDetalleProductos.setText("Detalles del producto");

        lblSubTotal.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblSubTotal.setText("SubTotal");

        txtSubTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSubTotalActionPerformed(evt);
            }
        });

        lblTotalIVA.setText("Total IVA (15%)");

        txtTotalIVA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalIVAActionPerformed(evt);
            }
        });

        lblTotal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTotal.setText("Total");

        txtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalActionPerformed(evt);
            }
        });

        btnImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/imprimirCompra.png"))); // NOI18N
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Imprimir(evt);
            }
        });

        lblFecha1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblFecha1.setText("Fecha:");

        btnCalcularTotal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/total.png"))); // NOI18N
        btnCalcularTotal.setText("CALCULAR TOTAL");
        btnCalcularTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularTotalActionPerformed(evt);
            }
        });

        lblProducto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblProducto.setText("Solicitudes");

        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cargarSoli.png"))); // NOI18N
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/aprobarSoli.png"))); // NOI18N
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/refresh.png"))); // NOI18N
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        tableDetallePedido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Usuario", "Producto", "Cantidad", "Precio", "Estado"
            }
        ));
        panelTableDetalleProductos1.setViewportView(tableDetallePedido);

        jLabel1.setText("IMPRIMIR");

        jLabel2.setText("REFRECAR APROBACIONES");

        jLabel3.setText("CARGAR SOLICITUD");

        jLabel4.setText("APROBAR SOLICITUD");

        javax.swing.GroupLayout panelGenerarOrdenCompraLayout = new javax.swing.GroupLayout(panelGenerarOrdenCompra);
        panelGenerarOrdenCompra.setLayout(panelGenerarOrdenCompraLayout);
        panelGenerarOrdenCompraLayout.setHorizontalGroup(
            panelGenerarOrdenCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGenerarOrdenCompraLayout.createSequentialGroup()
                .addGroup(panelGenerarOrdenCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelGenerarOrdenCompraLayout.createSequentialGroup()
                        .addGroup(panelGenerarOrdenCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelGenerarOrdenCompraLayout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(73, 73, 73)
                                .addComponent(btnImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelGenerarOrdenCompraLayout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jLabel2)
                                .addGap(51, 51, 51)
                                .addComponent(jLabel1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 301, Short.MAX_VALUE)
                        .addComponent(btnCalcularTotal))
                    .addGroup(panelGenerarOrdenCompraLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(panelGenerarOrdenCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panelGenerarOrdenCompraLayout.createSequentialGroup()
                                .addComponent(lblTotalIVA, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                                .addComponent(txtTotalIVA, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelGenerarOrdenCompraLayout.createSequentialGroup()
                                .addGroup(panelGenerarOrdenCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lblSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblTotal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(60, 60, 60)
                                .addGroup(panelGenerarOrdenCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                                    .addComponent(txtSubTotal))))))
                .addContainerGap())
            .addComponent(jSeparator1)
            .addGroup(panelGenerarOrdenCompraLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelGenerarOrdenCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelGenerarOrdenCompraLayout.createSequentialGroup()
                        .addComponent(lblProducto)
                        .addGap(272, 272, 272)
                        .addGroup(panelGenerarOrdenCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFecha1)
                            .addComponent(lblFecha))
                        .addGap(18, 18, 18)
                        .addGroup(panelGenerarOrdenCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblHoraActual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblFechaActual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(panelGenerarOrdenCompraLayout.createSequentialGroup()
                        .addGroup(panelGenerarOrdenCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelGenerarOrdenCompraLayout.createSequentialGroup()
                                .addGap(168, 168, 168)
                                .addComponent(jSeparator3))
                            .addGroup(panelGenerarOrdenCompraLayout.createSequentialGroup()
                                .addComponent(lblDetalleProductos)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(129, 129, 129))
                    .addComponent(panelTableDetalleProductos1, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
                    .addGroup(panelGenerarOrdenCompraLayout.createSequentialGroup()
                        .addComponent(panelTableDetalleProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 729, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGenerarOrdenCompraLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(panelGenerarOrdenCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGenerarOrdenCompraLayout.createSequentialGroup()
                        .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGenerarOrdenCompraLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(22, 22, 22)))
                .addGroup(panelGenerarOrdenCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelGenerarOrdenCompraLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel4))
                    .addGroup(panelGenerarOrdenCompraLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(82, 82, 82))
        );
        panelGenerarOrdenCompraLayout.setVerticalGroup(
            panelGenerarOrdenCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGenerarOrdenCompraLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(panelGenerarOrdenCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFecha1)
                    .addComponent(lblFechaActual)
                    .addComponent(lblProducto))
                .addGap(6, 6, 6)
                .addGroup(panelGenerarOrdenCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFecha)
                    .addComponent(lblHoraActual))
                .addGap(1, 1, 1)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelTableDetalleProductos1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panelGenerarOrdenCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelGenerarOrdenCompraLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelGenerarOrdenCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelGenerarOrdenCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(37, 37, 37)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelGenerarOrdenCompraLayout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(lblDetalleProductos)))
                .addGap(18, 18, 18)
                .addComponent(panelTableDetalleProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelGenerarOrdenCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSubTotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelGenerarOrdenCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(panelGenerarOrdenCompraLayout.createSequentialGroup()
                        .addGroup(panelGenerarOrdenCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelGenerarOrdenCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(108, 108, 108))
                    .addGroup(panelGenerarOrdenCompraLayout.createSequentialGroup()
                        .addGroup(panelGenerarOrdenCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTotalIVA)
                            .addComponent(txtTotalIVA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelGenerarOrdenCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTotal)
                            .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCalcularTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(147, 147, 147))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelGenerarOrdenCompra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelGenerarOrdenCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 636, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        try {
            //Inicio del metodo
            con = c.getConexion();
            stmt = con.createStatement();
            //Sentencia SQL
            ResultSet rs = stmt.executeQuery("SELECT productoSolicitud,cantidadSolicitud,precioSolicitud FROM solicitud WHERE estadoSolicitud = 'Aprobado'");
            modeloAprobado = new DefaultTableModel(null, titulosAprobados);
            while (rs.next()) {
                //Extraemos los valores de la Base de datos
                String NombreP = rs.getString("productoSolicitud");
                System.out.println(NombreP);
                filaAprobacio[0] = NombreP;
                filaAprobacio[1] = rs.getString("cantidadSolicitud");
                filaAprobacio[2] = rs.getString("precioSolicitud");
                int precio, cantidad;
                precio = Integer.valueOf(rs.getString("precioSolicitud"));
                cantidad = Integer.valueOf(rs.getString("cantidadSolicitud"));

                System.out.println(precio);

                filaAprobacio[3] = String.valueOf(cantidad * precio);

                modeloAprobado.addRow(filaAprobacio);
            }
            tableAprobaciones.setModel(modeloAprobado);

        } catch (SQLException e) {
            System.out.println(e.getMessage());

        }
        //Fin del metodo
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        //Inicio del metodo de eliminar
        if (tableDetallePedido.getSelectedRow() != -1) {
            String codigo = (String) modelo.getValueAt(tableDetallePedido.getSelectedRow(), 0);
            soliConecta.modificar(soli, codigo);
        }

    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        try {
            //Incio del metodo y la conexion 
            con = c.getConexion();
            stmt = con.createStatement();
            //Sentencia SQL
            ResultSet rs = stmt.executeQuery("select* from solicitud");
            modelo = new DefaultTableModel(null, titulos);
            //Aqui agregamos los valores a la tabla
            while (rs.next()) {
                fila[0] = rs.getString("idSolicitud");
                fila[1] = rs.getString("usuarioSolicitud");
                fila[2] = rs.getString("productoSolicitud");
                fila[3] = rs.getString("cantidadSolicitud");
                fila[4] = rs.getString("precioSolicitud");
                fila[5] = rs.getString("estadoSolicitud");
                modelo.addRow(fila);
            }
            tableDetallePedido.setModel(modelo);
            //Aqui van a la tabla
        } catch (Exception e) {
            System.out.println(e.getMessage());

        }
        //Fin del metodo


    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnCalcularTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularTotalActionPerformed
        //Variable de la tabla
        int fil;
        //Inico del metodo
        if (modeloAprobado.getRowCount() > 0) {
            if (tableAprobaciones.getSelectedRow() != -1) {
                fil = tableAprobaciones.getSelectedRow();
                calcularTotal();
            } else {
                JOptionPane.showMessageDialog(null, "Seleccione Una Fila");
            }
        } else {
            JOptionPane.showMessageDialog(null, "No hay Filas en la Tabla");
        }
        //Fin del metodo
    }//GEN-LAST:event_btnCalcularTotalActionPerformed

    private void Imprimir(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Imprimir
        try {
            //Incio del metodo 
            PrinterJob gap = PrinterJob.getPrinterJob();
            gap.setPrintable(this);
            boolean top = gap.printDialog();
            if (top) {
                gap.print();
            }
        } catch (PrinterException pex) {
            JOptionPane.showMessageDialog(null, "ERROR DE PROGRAMA", "ERROR\n" + pex, JOptionPane.INFORMATION_MESSAGE);
        }
        //Fin del metodo
    }//GEN-LAST:event_Imprimir

    private void txtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalActionPerformed

    private void txtTotalIVAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalIVAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalIVAActionPerformed

    private void txtSubTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSubTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSubTotalActionPerformed
//Metodo para poder redondear
    private double redondear(double num) {
        return Math.rint(num * 100 / 100);
    }

    private void eliminar() {
        //Variable del metodo
        int fil;
        //Incio del metodo
        if (modelo.getRowCount() > 0) {
            if (tableAprobaciones.getSelectedRow() != -1) {
                fil = tableAprobaciones.getSelectedRow();
                modelo.removeRow(fil);
                calcularTotal();
            } else {
                JOptionPane.showMessageDialog(null, "Seleccione Una Fila");
            }
        } else {
            JOptionPane.showMessageDialog(null, "No hay Filas en la Tabla");
        }
        //Fin del metodo
    }

    public void limpiarCampos() {
        //Limpiar campos
        txtSubTotal.setText("");
        txtTotalIVA.setText("");
        txtTotal.setText("");
        modelo.setValueAt(null, 0, 0);
        modelo.setValueAt(null, 0, 1);
        modelo.setValueAt(null, 0, 2);
        modelo.setValueAt(null, 0, 3);
        modelo.setValueAt(null, 1, 0);
        modelo.setValueAt(null, 1, 1);
        modelo.setValueAt(null, 1, 2);
        modelo.setValueAt(null, 1, 3);
        modelo.setValueAt(null, 2, 0);
        modelo.setValueAt(null, 2, 1);
        modelo.setValueAt(null, 2, 2);
        modelo.setValueAt(null, 2, 3);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAgregar;
    public javax.swing.JButton btnBuscar;
    public javax.swing.JButton btnCalcularTotal;
    private javax.swing.JButton btnEliminar;
    public javax.swing.JButton btnImprimir;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    public javax.swing.JLabel lblDetalleProductos;
    public javax.swing.JLabel lblFecha;
    public javax.swing.JLabel lblFecha1;
    public javax.swing.JLabel lblFechaActual;
    public javax.swing.JLabel lblHoraActual;
    private javax.swing.JLabel lblProducto;
    public javax.swing.JLabel lblSubTotal;
    public javax.swing.JLabel lblTotal;
    public javax.swing.JLabel lblTotalIVA;
    public javax.swing.JPanel panelGenerarOrdenCompra;
    private javax.swing.JScrollPane panelTableDetalleProductos;
    private javax.swing.JScrollPane panelTableDetalleProductos1;
    public javax.swing.JTable tableAprobaciones;
    public javax.swing.JTable tableDetallePedido;
    public javax.swing.JTextField txtSubTotal;
    public javax.swing.JTextField txtTotal;
    public javax.swing.JTextField txtTotalIVA;
    // End of variables declaration//GEN-END:variables

    @Override
    public int print(Graphics graf, PageFormat pagfor, int index) throws PrinterException {
        //Inicio del metodo Printable
        if (index > 0) {
            return NO_SUCH_PAGE;
        }
        Graphics2D hub = (Graphics2D) graf;
        hub.translate(pagfor.getImageableX() * 30, pagfor.getImageableY() * 30);
        hub.scale(0.5, 0.5);
        panelGenerarOrdenCompra.printAll(graf);
        return PAGE_EXISTS;
        //fin del metodo
    }

}
