package proyecto;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;




public class frmUsuarios extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmUsuarios
     */
    
    //Objetos instanciados
    UsuariosConexion uC = new UsuariosConexion();
    Usuario mod = new Usuario();
    Conexion c = new Conexion();
    
    //Variables Globales
    ResultSet rs = null;
    Connection con = null;
    Statement stmt = null; 
    DefaultTableModel modelo;
    
    //Arrays
    String titulos[] = {"id", "Nombre", "Usuario", "Clave", "Tipo usuario"};
    String fila[] = new String[6];
    String var, var1;

    public frmUsuarios() {
        initComponents();
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jLabel2 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        cmbTipoUsuario = new javax.swing.JComboBox<>();
        txtConfirma = new javax.swing.JPasswordField();
        jPanel1 = new javax.swing.JPanel();
        btnGuardar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        btnConsultaNombre = new javax.swing.JButton();
        btnConsultar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        btnEliminar = new javax.swing.JButton();
        btnModifica = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaUsuarios = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Registrar Usuario");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setText("USUARIO");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, -1, -1));

        txtUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtUsuarioKeyTyped(evt);
            }
        });
        getContentPane().add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 220, 20));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel3.setText("CLAVE");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, -1, -1));

        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });
        getContentPane().add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 220, -1));

        cmbTipoUsuario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cmbTipoUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Bodega", "Ventas", " ", " " }));
        cmbTipoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTipoUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(cmbTipoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 220, 30));
        getContentPane().add(txtConfirma, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, 220, 20));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DATOS PARA INGRESAR UN NUEVO USUARIO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 13))); // NOI18N

        btnGuardar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/addUsuario.png"))); // NOI18N
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        jLabel7.setText("GUARDAR");

        btnConsultaNombre.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnConsultaNombre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/browse.png"))); // NOI18N
        btnConsultaNombre.setText("BUSCAR POR NOMBRE");
        btnConsultaNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultaNombreActionPerformed(evt);
            }
        });

        btnConsultar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/consultarUser.png"))); // NOI18N
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel6.setText("USUARIO ID");

        txtId.setEditable(false);
        txtId.setBackground(new java.awt.Color(204, 204, 204));

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/deleteUsuario.png"))); // NOI18N
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnModifica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/modificarUs.png"))); // NOI18N
        btnModifica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificaActionPerformed(evt);
            }
        });

        tablaUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "usuarioID", "Nombre", "Usuario", "Password", "Tipo Usuario"
            }
        ));
        tablaUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaUsuariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaUsuarios);

        jLabel8.setText("MODIFICAR");

        jLabel9.setText("ELIMINAR");

        jLabel10.setText("CONSULTAR");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel1.setText("NOMBRE");

        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel4.setText("CONFIRMAR CLAVE");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel5.setText("TIPO DE USUARIO");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnModifica, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(169, 169, 169))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(103, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnConsultaNombre)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnConsultar))
                                .addComponent(jLabel9))
                            .addComponent(jLabel10))
                        .addGap(35, 35, 35))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnModifica, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addGap(4, 4, 4)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8))
                                .addGap(133, 133, 133))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(99, 99, 99)
                                .addComponent(btnConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(jLabel10)
                        .addGap(20, 20, 20)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addGap(3, 3, 3))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnConsultaNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 790, 470));
        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void actualizar() {
        //Variables del metodo
        String cadena1, cadena2, cadena3, cadena4, cadena5, cadena6;

        cadena1 = txtId.getText();
        txtId.setVisible(true);
        cadena2 = txtNombre.getText();
        cadena3 = txtUsuario.getText();
        cadena4 = txtPassword.getText();
        cadena5 = txtConfirma.getText();
        cadena6 = cmbTipoUsuario.getSelectedItem().toString();

        //inicio del metodo
        if (txtNombre.getText().equals("")) {

            javax.swing.JOptionPane.showMessageDialog(this, "1-. Consulte el nombre del cliente\n 2-. Actualice el dato deseado en el campo correspondiente", "AVISO!", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        } else {

            try {
                //Inicio de la conexion
                stmt = c.getConexion().createStatement();
                stmt.executeUpdate("update ignore usuarios set idUsuario= '" + cadena1 + "' , nombreUsuario = '" + cadena2 + "',usuario = '" + cadena3 + "',claveUsuario = '" + cadena4 + "', tipoUsuario = '" + cadena6 + "' where idUsuario = '" + txtId.getText() + "' || nombreUsuario = '" + txtNombre.getText() + "' || usuario = '" + txtUsuario.getText() + "' || claveUsuario = '" + txtPassword.getText() + "' || claveUsuario = '" + txtPassword.getText() + "'  || tipoUsuario = '" + cmbTipoUsuario.getSelectedItem().toString() + "'");
                //Fin de la conexion
                System.out.println("Los valores han sido Actualizados");
            } catch (SQLException e) {
                e.printStackTrace();       
                if (con != null) {

                    try {
                        con.close();
                        stmt.close();
                    } catch (Exception es) {
                        System.out.println(e.getMessage());
                    }
                }
            }
            javax.swing.JOptionPane.showMessageDialog(this, "Actualizado correctamente!", "AVISO!", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }
        //Limpiar la tabla
        this.txtId.setText("");
        this.txtNombre.setText("");
        this.txtUsuario.setText("");
        this.txtPassword.setText("");
        this.txtConfirma.setText("");
        //Fin del metodo
    }

    public void consulta() {
        //Variables del metodo
        var1 = var;
        String sql2 = "Select idUsuario, nombreUsuario, usuario, claveUsuario, tipoUsuario FROM usuarios where nombreUsuario = '" + var1 + "'";
        //inicio del metodo
        try {
            //Incio de la conexion
            String url = "jdbc:mysql://localhost:3306/pedidos";
            String usuario = "root";
            String contraseña = "";
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            con = DriverManager.getConnection(url, usuario, contraseña);
            stmt = con.createStatement();
            rs = stmt.executeQuery(sql2);
            //Fin de la conexion
            int i = 1;
            while (rs.next()) {
                //Lo que extraemos de la Base de datos
                String id = rs.getString("idUsuario");
                String inom = rs.getString("nombreUsuario");
                String inick = rs.getString("usuario");
                String ipass = rs.getString("claveUsuario");
                String itipo = rs.getString("tipoUsuario");
                
                //Colocamos la informacion 
                txtId.setText(id);
                txtNombre.setText(inom);
                txtUsuario.setText(inick);
                txtPassword.setText(ipass);
                txtPassword.setVisible(true);
                txtConfirma.setText(ipass);
                cmbTipoUsuario.setSelectedItem(itipo);

            }

        } catch (SQLException ex) {
            ex.printStackTrace();
        } catch (InstantiationException ex) {
            Logger.getLogger(frmProducto.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(frmProducto.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(frmProducto.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            if (rs != null) {
                try {
                    rs.close();
                } catch (SQLException ex) {
                    System.out.println(ex.getMessage());
                    ex.printStackTrace();
                }
            }
            if (stmt != null) {
                try {
                    stmt.close();
                } catch (SQLException ex) {
                    System.out.println(ex.getMessage());
                    ex.printStackTrace();
                }
            }
            if (con != null) {
                try {
                    con.close();
                } catch (SQLException ex) {
                    System.out.println(ex.getMessage());
                    ex.printStackTrace();
                }
            }

        }
//Fin del metodo   
}

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed

        //Inicio del metodo
        String pass = new String(txtPassword.getPassword());
        String passCon = new String(txtConfirma.getPassword());
        
        //Verificacion del password
        if (pass.equals(passCon)) {
            String nuevoPass = Hash.sha1(pass);
            mod.setNombreUsuario(txtNombre.getText());
            mod.setUsuario(txtUsuario.getText());
            mod.setClaveUsuario(nuevoPass);
            mod.setTipoUsuario(cmbTipoUsuario.getSelectedItem().toString());
            if (uC.registrar(mod)) {//Aqui enviamos la informacion del frm a la tabla de la Base de datos
                JOptionPane.showMessageDialog(null, "Registro exitoso");//Registramos si fue completado
                limpiar();
            } else {
                JOptionPane.showMessageDialog(null, "No se pudo guardar");//Registramos si no fue completado
            }
        } else {
            JOptionPane.showMessageDialog(null, "Claves no coinciden");//Si la claves no coinciden
        }
        //Fin del metodo
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if ((c < 'a' || c > 'z') && (c < 'A' || c < 'Z') && (c < ' ' || c > ' ')) {
            evt.consume();
        }

    }//GEN-LAST:event_txtNombreKeyTyped

    private void txtUsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsuarioKeyTyped
        char c = evt.getKeyChar();
        if ((c < 'a' || c > 'z') && (c < 'A' || c < 'Z') && (c < ' ' || c > ' '))
            evt.consume();
    }//GEN-LAST:event_txtUsuarioKeyTyped

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
       //Inicio del metodo
        try {
            //Incio de la conexion a la base de datos
            con = c.getConexion();
            stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery("SELECT* from usuarios");
            modelo = new DefaultTableModel(null, titulos);

            //Aqui le solicitamos la informacion a la tabla de la base de datos
            while (rs.next()) {

                fila[0] = rs.getString("idUsuario");
                fila[1] = rs.getString("nombreUsuario");
                fila[2] = rs.getString("usuario");
                fila[3] = rs.getString("claveUsuario");
                fila[4] = rs.getString("tipoUsuario");

                modelo.addRow(fila);
               
            }
            tablaUsuarios.setModel(modelo);
            //Se agrega a la tabla

        } catch (Exception e) {
            System.out.println(e.getMessage());
           
        }
        //Fin del metodo

    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnConsultaNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultaNombreActionPerformed
       //Variable del metodo
        String cap = "";
        
        //Incio del metodo/Se consulta aql usuario el nombre del usuario que desea ver
        var = javax.swing.JOptionPane.showInputDialog(this, "Nombre del usuario", "Consulta usuario", javax.swing.JOptionPane.QUESTION_MESSAGE);
        String sql = "SELECT* FROM  usuarios WHERE nombreUsuario = '" + var + "'";
        if (var == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "La accion fue cancelada", "AVISO!", javax.swing.JOptionPane.INFORMATION_MESSAGE);//Si la Accion fue cancelada
        } else {
            if (var.equals("")) {//Si coloco un nombre mal
                javax.swing.JOptionPane.showMessageDialog(this, "Favor de ingresar el nombre de usuario\nque desea consultar", "AVISO!", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            } else {
                try {
                    //Conexion con la base de datos
                    String url = "jdbc:mysql://localhost:3306/pedidos";
                    String usuario = "root";
                    String contraseña = "";

                    Class.forName("com.mysql.jdbc.Driver").newInstance();
                    con = DriverManager.getConnection(url, usuario, contraseña);
                    if (con != null) {
                        System.out.println("Se ha establecido una conexión a la base de datos "
                                + "\n " + url);
                    }

                    stmt = con.createStatement();
                    rs = stmt.executeQuery(sql);

                    while (rs.next()) {

                        cap = rs.getString("tipoUsuario");

                        if (cap.equals("Ventas") || cap.equals("Administrador") || cap.equals("Bodega")) {

                            consulta();
                        }
                    }   // fin del bucle While

                } catch (InstantiationException | IllegalAccessException | ClassNotFoundException | SQLException ex) {
                    Logger.getLogger(frmUsuarios.class.getName()).log(Level.SEVERE, null, ex);
                } finally {
                    if (con != null) {
                        try {
                            con.close();
                            stmt.close();
                        } catch (Exception e) {
                            System.out.println(e.getMessage());
                        }
                    }
                }
                if (!cap.equals("Ventas") && !cap.equals("Administrador") && !cap.equals("Bodega")) {
                    javax.swing.JOptionPane.showMessageDialog(this, "El usuario no fue encontrado\n", "ERROR!", javax.swing.JOptionPane.ERROR_MESSAGE);
                }
            }
        }


    }//GEN-LAST:event_btnConsultaNombreActionPerformed

    private void tablaUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaUsuariosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tablaUsuariosMouseClicked

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
       //Variables y contador del metodo
        int r = 0;
        int fila = tablaUsuarios.getSelectedRow();
        
        //Inicio del metodo
        if (fila == -1) {
            JOptionPane.showMessageDialog(null, "Para eliminar un registro debe de seleccionar un usuario en la tabla");
        } else {
            int id = Integer.parseInt(tablaUsuarios.getValueAt(fila, 0).toString());
            r = uC.eliminarUsuarios(id);//Aqui enviamos la informacion a la clase conexion
            if (r == 1) {
                limpiar();
                JOptionPane.showMessageDialog(null, "Usuario eliminado con exito");//Si se completo el metodo de forma correcta
            } else {
                JOptionPane.showMessageDialog(null, "Usuario NO eliminado");//Si no se completa el metodo de forma correcta
            }
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void cmbTipoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTipoUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbTipoUsuarioActionPerformed

    private void btnModificaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificaActionPerformed
        // TODO add your handling code here:
                actualizar();//Metode de actualizar

    }//GEN-LAST:event_btnModificaActionPerformed

    //Limpia campos
    private void limpiar() {
        txtConfirma.setText("");
        txtId.setText("");
        txtNombre.setText("");
        txtPassword.setText("");
        txtUsuario.setText("");
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultaNombre;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnModifica;
    private javax.swing.JComboBox<String> cmbTipoUsuario;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaUsuarios;
    private javax.swing.JPasswordField txtConfirma;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
